//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberpunk2020Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberpunk2020Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma
        ///Olivia
        ///Ava
        ///Isabella
        ///Sophia
        ///Charlotte
        ///Mia
        ///Amelia
        ///Harper
        ///Evelyn
        ///Abigail
        ///Emily
        ///Elizabeth
        ///Mila
        ///Ella
        ///Avery
        ///Sofia
        ///Camila
        ///Aria
        ///Scarlett
        ///Victoria
        ///Madison
        ///Luna
        ///Grace
        ///Chloe
        ///Penelope
        ///Layla
        ///Riley
        ///Zoey
        ///Nora
        ///Lily
        ///Eleanor
        ///Hannah
        ///Lillian
        ///Addison
        ///Aubrey
        ///Ellie
        ///Stella
        ///Natalie
        ///Zoe
        ///Leah
        ///Hazel
        ///Violet
        ///Aurora
        ///Savannah
        ///Audrey
        ///Brooklyn
        ///Bella
        ///Claire
        ///Skylar
        ///Lucy
        ///Paisley
        ///Everly
        ///Anna
        ///Caroline
        ///Nova
        ///Genesis
        ///Emilia
        ///Kennedy
        ///Samantha
        ///Maya
        ///Willow
        ///Kinsley
        ///Naomi
        ///Aaliyah
        ///Elena [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adi
        ///Agner
        ///Ajax
        ///Alan
        ///Alt
        ///Altair
        ///Amp
        ///Andon
        ///Andrew
        ///App
        ///Arax
        ///Arin
        ///Arp
        ///Ash
        ///Atto
        ///Audio
        ///Avi
        ///Axis
        ///Batch
        ///Baud
        ///Balun
        ///Ben
        ///Beep
        ///Bic
        ///Bing
        ///Bit
        ///Blade
        ///Board
        ///Bob
        ///Boot
        ///Bot
        ///Box
        ///Buddy
        ///Bug
        ///Bus
        ///Byte
        ///Cam
        ///Cap
        ///Cas
        ///Case
        ///Cell
        ///Cermet
        ///Charles
        ///Chip
        ///Cipher
        ///Claude
        ///Clifford
        ///Cloud
        ///Click
        ///Clip
        ///Codec
        ///Code
        ///Coil
        ///Cord
        ///Crash
        ///Cron
        ///Crypto
        ///Cyber
        ///Cybo
        ///Cyrix
        ///Daemon
        ///Daryl
        ///Dash
        ///David
        ///Degauss
        ///Del
        ///Digit
        ///Diode
        ///Dock
        ///Dom
        ///Dyne
        ///Edgar
        ///Error
        ///Fax
        ///Flash
        ///Frag
        ///Glitch
        ///Gort
        ///Gram
        ///Grep
        ///Grid
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shy and secretive
        ///Rebellious, antisocial and violent
        ///Arrogant, proud and aloof
        ///Moody, rash and headstrong
        ///Picky, fussy and nervous
        ///Stable and serious
        ///Silly and fluffheaded
        ///Sneaky and deceptive
        ///Intellectual and detatched
        ///Friendly and outgoing
        ///A parent
        ///A brother or sister
        ///A lover
        ///A friend
        ///Yourself
        ///A pet
        ///A Teacher or mentor
        ///A public figure
        ///A personal hero
        ///No one
        ///Money
        ///Honor
        ///Your word
        ///Honesty
        ///Knowledge
        ///Vengeance
        ///Love
        ///Power
        ///Having a good time
        ///Friendship
        ///Neutral
        ///Neutral
        ///I like almo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Motivation {
            get {
                return ResourceManager.GetString("Motivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corp (Executive, Officer, Union Rep, Stock Trader, Bureaucrat, Manager)   You are a company man, you are an expert at promoting and utilizing the resources your employer or business allows you.  You are the Power Broker, the CEO, the VIP. 
        ///Awareness/Notice, Human Perception, Education, Library Search, Social, Persuasion, Stock Market, Wardrobe &amp; Style, Personal Grooming
        ///
        ///Cop (Police Officer, Guardsman, MP, Sheriff, Peacekeeper, Lawman) You uphold the law, you have the authority to arrest lawbreakers, que [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villanueva
        ///Adams
        ///Rios
        ///Pacheco
        ///Henry
        ///Pena
        ///Mullen
        ///Nicholson
        ///Keller
        ///Fischer
        ///Leon
        ///Frank
        ///Stafford
        ///Bauer
        ///Kramer
        ///Douglas
        ///Carter
        ///May
        ///Bird
        ///Lane
        ///Phelps
        ///Davenport
        ///Conley
        ///Stevens
        ///Lucero
        ///Spence
        ///Bell
        ///Maldonado
        ///Lester
        ///Bright
        ///Medina
        ///Boyer
        ///Raymond
        ///Murillo
        ///Melton
        ///Pham
        ///Kelly
        ///Bullock
        ///Schmidt
        ///Nelson
        ///Frye
        ///Maxwell
        ///Barrera
        ///Hancock
        ///Reese
        ///Vincent
        ///Kim
        ///Calhoun
        ///Fowler
        ///Garcia
        ///Huff
        ///Key
        ///Ortiz
        ///Beck
        ///Shaffer
        ///Jensen
        ///Chen
        ///Valenzuela
        ///Miller
        ///Chaney
        ///Gilbert
        ///Bruce
        ///Benson
        ///Ramirez
        ///Marsh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
    }
}
